### ISSUE TITLE
eqMac2 can't install drivers on Catalina 10.15.2

### ISSUE THREAD

**Issue by nutzaalex** [nodeful/eqMac2#184]
I can't install the necessary drivers since Catalina's System folder is read only nowadays..., is there a predefined place where the driver files should exist?

if so could you please share with me the path and I'm guessing I should copy paste the drivers from the .dmg installer in there

I am aware this could be bypassed disabling various security services on the mac, I'm not familiar/ confortable doing that though...

Or is there a sure & easy method to disable the security and reenable it after the drivers install?

Thanks

**Comment by nutzaalex** [comment]
Steps that I took in order to install the software:

First, uninstall the application that may have partially or incorrectly installed, if applicable
Reboot the system and hold down Command+R (⌘+R) keys simultaneously when you hear the startup chime; this will boot macOS into Recovery Mode
Once in Recovery mode, open a Terminal window from the Utilities drop-down menu at the top of the screen
Type in the Terminal: csrutil disable
Hit Enter, and you’ll see a message saying that System Integrity Protection has been disabled and that the Mac needs to restart for changes to take effect
Restart the machine (enter reboot in the Terminal, or use the Apple menu to find the Restart option)
Install the desired software


To re-enable SIP after installation:

Reboot into Recovery Mode again (⌘+R at system chime)
Open a Terminal and enter: csrutil enable
Reboot

Credits:
https://support.studionetworksolutions.com/hc/en-us/articles/115003839246-How-to-disable-Systems-Integrity-Protection-SIP-in-macOS

**Comment by lalala** [comment]
This did not resolve the issue for me.

**Comment by nutzaalex** [comment]
@lalala after disabling SIP in recovery, boot as usual, and in terminal do "sudo mount -uw /" this should make the system partition remounted as write not readonly, and try to install, the partition becomes read only again after a restart. But remember to disable SIP in recovery again after you've installed it.

**Comment by grgur** [comment]
Thanks @nutzaalex, this did the trick for me:

```sh
sudo mount -uw /
```

**Comment by riggedpie** [comment]
sudo mount -uw/ came up with "illegal option" This was after I disabled the csrutil too. What am I doing wrong?

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.

**Comment by AudioTechSoup** [comment]
The new eqMAC is not as good as eqmac2... it was great when it was simple. I downloaded the new Raman and now my sound is inconsistent. I just want to update the driver for eqmac2! PLEASE! Ive donated to the EQ as well...
