### ISSUE TITLE
Readme is not clear -- how to run??

### ISSUE THREAD

**Issue by jaywalkerpaz** [nodeful/eqMac2#186]
Hello! you are probably an amazing developer! I loved that you included how to install this. But.. how do you run this?

**Comment by carlonoelle** [comment]
What do you mean? Just download and double click it: https://bitgapp.com/eqmac/

**Comment by jaywalkerpaz** [comment]
thank you for the reply! I downloaded through homebrew, I guess I didn't
realize I could open it if installed through there.. the app itself is
definitely straightforward. Also, I have to say, FANTASTIC product. You are
changing my life with this ability thanks.

One thing I'd like is for it to auto-detect when I plug in my headphones vs
when I don't, and maybe do an auto-switch as it happens without the app?
Otherwise, A+ man, fantastic fantastic fantastic.

**Comment by nodeful** [comment]
Hey everyone 👋 
I will be open sourcing the new version of eqMac, therefore, I am closing this issue and repository as I will be transfering [nodeful/eqMac2](https://github.com/nodeful/eqMac2) repo to [bitgapp/eqMac](https://github.com/bitgapp/eqMac)
Please bear with me for the next couple of days as I setup that new repo. The eqMac2 code will be living in the [old-eqMac2](https://github.com/bitgapp/eqMac/tree/old-eqmac2) branch if anyone is interested in referencing it for whatever reason.
Please try out the new version and report bugs to the new repo.
Thanks for using eqMac.
